// Code generated by go-swagger; DO NOT EDIT.

package rus_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RusProfileGetInfoHandlerFunc turns a function with the right signature into a rus profile get info handler
type RusProfileGetInfoHandlerFunc func(RusProfileGetInfoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RusProfileGetInfoHandlerFunc) Handle(params RusProfileGetInfoParams) middleware.Responder {
	return fn(params)
}

// RusProfileGetInfoHandler interface for that can handle valid rus profile get info params
type RusProfileGetInfoHandler interface {
	Handle(RusProfileGetInfoParams) middleware.Responder
}

// NewRusProfileGetInfo creates a new http.Handler for the rus profile get info operation
func NewRusProfileGetInfo(ctx *middleware.Context, handler RusProfileGetInfoHandler) *RusProfileGetInfo {
	return &RusProfileGetInfo{Context: ctx, Handler: handler}
}

/*
	RusProfileGetInfo swagger:route POST /rusprofile/info RusProfile rusProfileGetInfo

RusProfileGetInfo rus profile get info API
*/
type RusProfileGetInfo struct {
	Context *middleware.Context
	Handler RusProfileGetInfoHandler
}

func (o *RusProfileGetInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRusProfileGetInfoParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
