// Code generated by go-swagger; DO NOT EDIT.

package rus_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/daniilmikhaylov2005/shtraf/swaggerui/models"
)

// RusProfileGetInfoOKCode is the HTTP code returned for type RusProfileGetInfoOK
const RusProfileGetInfoOKCode int = 200

/*
RusProfileGetInfoOK A successful response.

swagger:response rusProfileGetInfoOK
*/
type RusProfileGetInfoOK struct {

	/*
	  In: Body
	*/
	Payload *models.APICompany `json:"body,omitempty"`
}

// NewRusProfileGetInfoOK creates RusProfileGetInfoOK with default headers values
func NewRusProfileGetInfoOK() *RusProfileGetInfoOK {

	return &RusProfileGetInfoOK{}
}

// WithPayload adds the payload to the rus profile get info o k response
func (o *RusProfileGetInfoOK) WithPayload(payload *models.APICompany) *RusProfileGetInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rus profile get info o k response
func (o *RusProfileGetInfoOK) SetPayload(payload *models.APICompany) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RusProfileGetInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
RusProfileGetInfoDefault An unexpected error response.

swagger:response rusProfileGetInfoDefault
*/
type RusProfileGetInfoDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.RuntimeError `json:"body,omitempty"`
}

// NewRusProfileGetInfoDefault creates RusProfileGetInfoDefault with default headers values
func NewRusProfileGetInfoDefault(code int) *RusProfileGetInfoDefault {
	if code <= 0 {
		code = 500
	}

	return &RusProfileGetInfoDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the rus profile get info default response
func (o *RusProfileGetInfoDefault) WithStatusCode(code int) *RusProfileGetInfoDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the rus profile get info default response
func (o *RusProfileGetInfoDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the rus profile get info default response
func (o *RusProfileGetInfoDefault) WithPayload(payload *models.RuntimeError) *RusProfileGetInfoDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rus profile get info default response
func (o *RusProfileGetInfoDefault) SetPayload(payload *models.RuntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RusProfileGetInfoDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
