// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APICompany api company
//
// swagger:model apiCompany
type APICompany struct {

	// fullname director
	FullnameDirector string `json:"fullname_director,omitempty"`

	// inn
	Inn string `json:"inn,omitempty"`

	// kpp
	Kpp string `json:"kpp,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this api company
func (m *APICompany) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api company based on context it is used
func (m *APICompany) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APICompany) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APICompany) UnmarshalBinary(b []byte) error {
	var res APICompany
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
